"""add secret_id

Revision ID: b6ba67f70c2d
Revises: 5cb4cc2fa357
Create Date: 2026-08-21 19:17:39.135120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ba67f70c2d'
down_revision: Union[str, Sequence[str], None] = '5cb4cc2fa357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secrets', sa.Column('secret_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'secrets', ['secret_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'secrets', type_='unique')
    op.drop_column('secrets', 'secret_id')
    # ### end Alembic commands ###
